version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: npm run test

  analyze:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: npm run audit


workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
